api/urls.py
from django.urls import path, re_path, include
from .views import *

app_name = 'v1'

urlpatterns = [
    path('isemailexist/', IsEmailExist.as_view()),
    path('profile/', UserProfile.as_view()),
    path('dashboard/', UserDashboard.as_view()),
    path('data-history/', HealthDataHistoryAPIView.as_view()),
    path('signup/', UserSignUp.as_view(), name='signup'),
    path('token/', MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', MyTokenRefreshView.as_view(), name='token_refresh'),
    path('password/reset/', PasswordResetView.as_view(), name='rest_password_reset'),
    path('password/reset/confirm/', PasswordResetConfirmView.as_view(), name='rest_password_reset_confirm'),
    path('password/change/', PasswordChangeView.as_view(), name='rest_password_change'),
    path('policy/', policy),
    path('policy-intime/', PolicyIntime.as_view(), name='policy'),
    path('result/', Results.as_view(), name='result'),
    path('resultdata/', ResultsData.as_view(), name='resultdata'),
    path('countries/', countries_dict),
    path('genders/', genders_dict),
    path('getfirstresulttime/', getfirstresulttime),
    path('user_cardioactivity/create/', CreateUserCardioactivity.as_view()),
    path('user_cardioactivity/<int:start_date>/<int:end_date>/', UserCardioactivity.as_view()),
    path('recomendations/', UserRecomendations.as_view()),
    path('image/', Image.as_view(), name='image'),
    path('disease/', DiseaseViews.as_view()),
    path('cardio_recomendations/', CardioRecomendations.as_view()),
    path('user_profile/', ProfileUser.as_view()),
    path('med_card/', MedCard.as_view()),
    path('info/', InformationView.as_view(), name='info'),
    path('login/', include('rest_social_auth.urls_jwt_pair')),
    path('login/', include('rest_social_auth.urls_session')),
]

landing/urls.py
from django.urls import path
from . import views

app_name = 'landing'

urlpatterns = [
    path('', views.index, name='index'),
    path('petitions/', views.petitions, name='petitions'),
]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name='index'),
    path('privacy/', views.privacy, name='privacy'),
    path('terms/', views.terms, name='terms'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('application/', views.application, name='application'),
    path('antivirus/', views.antivirus, name='antivirus'),
    path('company-mission/', views.companyMission, name='company-mission'),
    path('investor-relations/', views.investorRelations, name='investor-relations'),
    path('doctor-relations/', views.doctorRelations, name='doctor-relations'),
    path('vacancies/', views.vacancies, name='vacancies'),
    path('support-research/', views.supportResearch, name='support-research'),
    path('articles/', views.articles, name='articles'),
    path('additional/', views.additional, name='additional'),
    path('articles/<slug:pubmed_id>/', views.article_detail, name='article_detail'),
    path('send-email/', views.send_email, name='send_email'),
]

landing/models.py
from django.db import models

# Create your models here.

pages/forms.py
import os

from django import forms
from django.utils.translation import gettext_lazy as _
from django.core.validators import ValidationError

from .models import AppForm, Contact


# def validate_file_extension(value):
#     ext = os.path.splitext(value.name)[1]  # [0] returns path+filename
#     valid_extensions = ['.pdf', '.doc', '.docx', '.jpg', '.png', '.xlsx', '.xls']
#     if not ext.lower() in valid_extensions:
#         raise ValidationError(u'Unsupported file extension.')


class ApplicationForm(forms.ModelForm):
    use_required_attribute = False

    name = forms.CharField(label=False,
                           widget=forms.TextInput(
                               attrs={'placeholder': _("Enter your name"), 'required': False}))
    message = forms.CharField(label=False, required=False,
                              widget=forms.Textarea(
                                  attrs={'placeholder': _("Message"), 'rows': 2, 'cols': 40, 'required': False}))

    email = forms.EmailField(label=False,
                             widget=forms.TextInput(
                                 attrs={'placeholder': _("Enter your email"), 'required': False}))

    class Meta:
        model = AppForm
        fields = ('name', 'message', 'email')


class ContactForm(forms.ModelForm):
    use_required_attribute = False

    name = forms.CharField(label=False,
                           widget=forms.TextInput(
                               attrs={'placeholder': _("Enter your name"), 'required': False}))
    message = forms.CharField(label=False, required=False,
                              widget=forms.Textarea(
                                  attrs={'placeholder': _("Message"), 'rows': 2, 'cols': 40, 'required': False}))

    email = forms.EmailField(label=False,
                             widget=forms.TextInput(
                                 attrs={'placeholder': _("Enter your email"), 'required': False}))

    phone_number = forms.RegexField(label=False,
                            regex=r'^\+?1?\d{9,15}$',
                            widget=forms.TextInput(
                                 attrs={'placeholder': _("Enter your phone number"), 'required': False})
                            )

    class Meta:
        model = Contact
        fields = ('name', 'message', 'email', 'phone_number')


class SendingPresentationForm(forms.Form):
    title = forms.CharField(required=True, label=_('Title'),
                            widget=forms.TextInput(
                                attrs={'readonly': 'readonly', 'placeholder': _('Title'), 'required': False}))
    name = forms.CharField(label=False, required=True,
                           widget=forms.TextInput(
                               attrs={'placeholder': _("Enter your name"), 'required': False}))
    email = forms.EmailField(label=False, required=True,
                             widget=forms.TextInput(
                                 attrs={'placeholder': _("Enter your email"), 'required': False}))
    message = forms.CharField(label=False, required=True,
                              widget=forms.Textarea(
                                  attrs={'placeholder': _("Message"), 'rows': 2, 'cols': 40, 'required': False}))
    file = forms.FileField(label=False, required=False,
                           widget=forms.FileInput(
                              attrs={'placeholder': _("Choose File"), 'required': False}))

landing/views.py
import mimetypes
import requests

from django.shortcuts import render
from django.conf import settings


def index(request):
    return render(request, 'base_landing.html')


def petitions(request):
    return render(request, 'petitions.html')

pages/templates/about.html
{% extends '_base.html' %}
{% load i18n %}

{% block head %}
    {% include 'includes/google-event-snippet.html' %}

    <title>Longevity InTime - {% trans 'About' %}</title>
{% endblock head %}

{% block content %}
<section class="main about container-fluid d-flex align-items-center">
    <div class="container justify-content-center mt-4 pt-4">
        <h1 class="text-uppercase section-heading text-dark text-center mb-4 py-4">LONGEVITY INTIME</h1>

        <section class="text-left text-secondary mb-2 pb-2 mx-lg-5 px-lg-5">
            {% if LANGUAGE_CODE == 'en' %}
                <p>
                  Longevity Intime is a company developing online technology, which enables early diagnosis of diseases using
                  real-time biometrics from the human body.
                </p>
                <p>
                  Personal electronic gadgets (smart-watches, fitness-bracelets, etc.), portable containers for remote sampling
                  of biomaterial (blood, urine, etc.), software code, and machine learning algorithms help to diagnose and
                  predict the likelihood of developing serious diseases in the extremely early, formerly diagnosable stages,
                  and provide recommendations for their prevention. Early diagnosis of diseases and taking the necessary
                  measures when they are detected can have a positive effect on a person's life expectancy.
                </p>
                <p>
                  The technology developed by us quickly analyzes more than 400 parameters of the physical state of the
                  human body in real-time. Thanks to this, the user receives data on his health status in the mobile
                  application and on the website, as well as personal recommendations aimed at improving his health condition.
                  The recommendations provided are generated by artificial intelligence, verified by specialists, and based
                  on Big Data obtained from proven clinical trials over the past 50 years in the G20 countries.
                </p>
                <p>
                  The Longevity InTime team includes experienced biotechnologists, award-winning scientists, developers,
                  and experienced executives with years of experience. Together we are solving the global problem of life
                  expectancy for each person and for all mankind.
                </p>
                <p>
                  The team of 30 developers from 6 countries all over the world is probably the largest biotech company in
                  the world. Each and every member of which believes in the company's goals and global mission.
                </p>
                <p>
                  Our goal is to extend a person's life by more than 20 active and happy years without any restrictions to him.
                  We respond to both the personal and public interests of every country on Earth.
                </p>
                <p>
                  We believe that you want to see how your children will raise their grandchildren. We intend to deliver you
                  this product InTime!
                </p>
                <p>
                  Additional information about the company in
                  <a 
                    href="https://www.ai-businessdirectory.net/wilmington/ai-companies-providing-services-for-healthcare/longevity-intime-biotech?from=badge"
                    target="_blank"
                  >
                    Artificial Intalligence Business Directory
                  </a>
                </p>

                <div class="mt-5 mb-4">
                    <a href="https://youtube.com/watch?v=UYV36MUy7qg&feature=youtu.be" target="_blank">Video: Harvard’s Medical School Principal Vadim Gladyshev</a>
                </div>

                <div class="my-4 text-center col video-container">
                    <iframe src="https://www.youtube.com/embed/UYV36MUy7qg" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                </div>

                <div class="mt-5 mb-4">
                    <a href="https://www.youtube.com/watch?v=OHvEFObWjc8&feature=youtu.be" target="_blank">"The Lord of Longevity. Alexey Moskalev". Documentary</a>
                </div>

                <div class="my-4 text-center col video-container">
                    <iframe width="560" height="315" src="https://www.youtube.com/embed/OHvEFObWjc8" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                </div>
                <!--
                <a href="{% url 'pages:additional' %}">
                    Additional
                </a>

                <p class="my-5"><em>This information is informational and educational in nature. Consult a specialist.</em></p>
              -->
            {% endif %}

            {% if LANGUAGE_CODE == 'ru' %}
                <p>
                  Longevity Intime - это компания, которая занимается разработкой онлайн технологии и позволяет
                  диагностировать заболевания на ранних стадиях при помощи биометрических показателей человеческого организма,
                  собираемых в реальном времени.
                </p>
                <p>
                  Персональные электронные гаджеты (smart-часы, фитнес-браслеты и прочее), портативные контейнеры
                  для дистанционного забора биоматериала (кровь, моча и др.), программный код и алгоритмы машинного
                  обучения помогают диагностировать и спрогнозировать вероятность развития тяжёлых заболеваний на ранних,
                  до этого не диагностируемых, стадиях и предоставить рекомендации по их предотвращению. Ранняя диагностика
                  заболеваний и принятие необходимых мер при их обнаружении способны положительно повлиять на продолжительность
                  жизни человека.
                </p>
                <p>
                  Разработанная нами технология оперативно анализирует более 400 параметров физического состояния человеческого
                  организма в реальном времени. Благодаря этому пользователь получает в мобильном приложении и на сайте
                  данные о состоянии своего здоровья, а также персональные рекомендации, которые призваны улучшить состояние
                  его здоровья. Предоставляемые рекомендации сгенерированы искусственным интеллектом, проверенны специалистами
                  и базируются на Big Data полученных из доказанных клинических испытаний за последние 50 лет в странах G20.
                </p>
                <p>
                  В команду Longevity InTime входят опытные биотехнологи, титулованные учёные, разработчики и опытные топ-менеджеры
                  с многолетним опытом. Вместе мы решаем глобальную проблему долголетия как каждого человека, так и всего человечества.
                </p>
                <p>
                  Команда из 30 разработчиков из 6 стран мира - возможно, крупнейшая в мире команда биотехнологической компании, каждый
                  учасник которой верит в цели и глобальную миссию компании.
                </p>
                <p>
                  Наша цель - продлить жизнь человека более, чем на 20 активных и счастливых лет без каких-либо ограничений для него.
                  Мы отвечаем как личным, так и общественным интересам каждой страны на Земле.
                </p>
                <p>
                  Мы верим, что Вы хотите увидеть, как ваши дети будут растить своих внуков. Мы намерены доставить Вам этот продукт
                  InTime (в срок)!
                </p>
                <p>
                  Дополнительная информация о компании в
                  <a 
                    href="https://www.ai-businessdirectory.net/wilmington/ai-companies-providing-services-for-healthcare/longevity-intime-biotech?from=badge"
                    target="_blank"
                  >
                    Artificial Intalligence Business Directory
                  </a>
                </p>


                <div class="mt-5 mb-4">
                    <a href="https://youtube.com/watch?v=UYV36MUy7qg&feature=youtu.be" target="_blank">Видео: Вадим Гладышев, глава Медицинской школы Гарварда</a>
                </div>

                <div class="my-4 text-center col video-container">
                    <iframe src="https://www.youtube.com/embed/UYV36MUy7qg" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                </div>


                <div class="mt-5 mb-4">
                    <a href="https://www.youtube.com/watch?v=OHvEFObWjc8&feature=youtu.be" target="_blank">"Повелитель долголетия. Алексей Москалев". Документальный фильм</a>
                </div>

                <div class="my-4 text-center col video-container">
                    <iframe width="560" height="315" src="https://www.youtube.com/embed/OHvEFObWjc8" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                </div>
                <!--
                <a href="{% url 'pages:additional' %}">
                    Дополнительно
                </a>

                <p class="my-5"><em>Сведения носят информационно-образовательный характер. Проконсультируйтесь со специалистом.</em></p>
                -->
            {% endif %}
        </section>

        <section class="d-flex flex-wrap justify-content-center my-4">
            <a href={% url 'pages:company-mission' %} class="text-uppercase text-center m-3 p-2">{% trans 'Сompany mission' %}</a>
            <a href={% url 'pages:investor-relations' %} class="text-uppercase text-center m-3 p-2">{% trans 'Investor relations' %}</a>
            <a href={% url 'pages:doctor-relations' %} class="text-uppercase text-center m-3 p-2">{% trans 'Doctor relations' %}</a>
            <a href={% url 'pages:support-research' %} class="text-uppercase text-center m-3 p-2">{% trans 'Support research' %}</a>
            <a href={% url 'pages:vacancies' %} class="text-uppercase text-center m-3 p-2">{% trans 'Vacancies' %}</a>
        </section>

        <section class=" mb-4 pb-4 text-center">
            {% include 'includes/preorder-button.html' %}
        </section>
    </div>
</section>
{% endblock %}

pages/templates/application.html
{% extends '_base.html' %}
{% load i18n %}
{% load bootstrap4 %}
{% load static %}

{% block head %}
<title>Longevity InTime - {% trans 'Pre order' %}</title>
{% endblock head %}

{% block content %}
<section class="main pre-order container-fluid d-flex align-items-center">
  <div class="container my-4 py-4">
    <form method="post" class="card shadow p-4">
      <h2 class="section-heading mb-4 w-100">{% trans 'Pre order' %}</h2>

      <div class="text-secondary pb-2">
        <a href='https://drive.google.com/file/d/1e9d5VDjSMdaFisqSkMDdbvuN2uP-kz0F/view?usp=sharing' target="_blank">
          {% trans 'To learn more please download' %}
        </a>
      </div>

      {% bootstrap_messages %}

      {% csrf_token %}
      <div class="form-group mb-0">
        {% bootstrap_field form.name %}
      </div>

      <div class="form-group mb-0">
        {% bootstrap_field form.message %}
      </div>

      {% if request.user.is_authenticated %}
        <div class="form-group">
          <input type="text" class="form-control" id="email" name="email" placeholder='{% trans "Enter your email" %}' value='{{ user.email }}' >
        </div>

      {% else %}
        <div class="form-group">
          {% bootstrap_field form.email %}
        </div>
      {% endif %}

      <div class="text-center">
        <button class="btn btn-primary" type="submit">{% trans 'Send' %}</button>
      </div>
    </form>
  </div>
</section>

<script>
  // Check Submit button activity
  const submitButton = document.querySelector('button[type="submit"]')

  const nameInput = document.querySelector('#id_name')
  const messagelnput = document.querySelector('#id_message')
  const emailInput = document.querySelector('#email')

  function checkButtonActivity() {
    const inputAllFilled = nameInput.value && emailInput.value && messagelnput.value

    if (inputAllFilled) {
      submitButton.removeAttribute("disabled")
    } else {
      submitButton.setAttribute("disabled", "true")
    }
  }

  checkButtonActivity()

  for (const input of [nameInput, messagelnput, emailInput]) {
    input.addEventListener('input', checkButtonActivity)
  }
</script>
{% endblock content %}

pages/templates/articles.html
{% extends '_base.html' %}
{% load i18n %}
{% load bootstrap4 %}
{% load static %}

{% block head %}
<title>Longevity InTime - {% trans 'Pre order' %}</title>
{% endblock head %}

{% block content %}
<div class="container align-items-center" style="margin-top: 100px">

    {% for article in articles %}
        <div class="alert alert-primary" role="alert">
{#            <a href="{% url 'pages:article_detail' article.fields.article_title|slugify %}">{{ article.fields.article_title }}</a>#}
            <a href="{% url 'pages:article_detail' article.fields.article_id_pubmed %}">{{ article.fields.article_title }}</a>
        </div>
    {% endfor %}

    <nav aria-label="...">
        <ul class="pagination">
            <li class="page-item {% if prev_page == "0" %} disabled {% else %} enabled {% endif %}">
                <a class="page-link" href="?page={{ prev_page }}" tabindex="-1">Previous</a>
            </li>
{#            <li class="page-item"><a class="page-link" href="#">1</a></li>#}
            <li class="page-item active">
                <a class="page-link" href="#">{{ page }}<span class="sr-only">(current)</span></a>
            </li>
{#            <li class="page-item"><a class="page-link" href="?page=">3</a></li>#}
            <li class="page-item">
                <a class="page-link" href="?page={{ next_page }}">Next</a>
            </li>
        </ul>
    </nav>

</div>
{% endblock content %}

pages/templates/send_email.html
{% extends '_base.html' %}
{% load i18n %}
{% load bootstrap4 %}

{% block head %}
<title>Longevity InTime - {% trans 'Send email' %}</title>
{% endblock head %}

{% block content %}
<section class="main contact container-fluid d-flex align-items-center">
    <div class="container justify-content-center my-4 py-4 px-0">

        <form method="post" enctype="multipart/form-data" content="text/html; charset=UTF-8" class="card shadow p-4">
            <h2 class="section-heading text-dark mb-4 w-100">{% trans 'Send email' %}</h2>

            {% csrf_token %}
            {% bootstrap_messages %}
            <div class="form-group mb-3">
                {% bootstrap_field form.title %}
            </div>
            {% if request.user.is_authenticated %}
                <div class="form-group  mb-3">
                    <input type="text" class="form-control" id="email" name="email" placeholder='Введите Ваш email' value='{{ user.email }}' >
                </div>
            {% if user.first_name %}
                <div class="form-group  mb-3">
                    <input type="text" class="form-control" id="name" name="name" placeholder='Введите Ваше Имя' value='{{ user.first_name }} {% if user.last_name %}{{ user.last_name }}{% endif %}' >
                </div>
            {% else %}
            <div class="form-group mb-3">
                {% bootstrap_field form.name %}
            </div>
            {% endif %}
            {% else %}
                <div class="form-group  mb-0">
                    {% bootstrap_field form.email %}
                </div>
                <div class="form-group mb-3">
                    {% bootstrap_field form.name %}
                </div>
            {% endif %}

            <div class="form-group mb-3">
                {% bootstrap_field form.message %}
            </div>

            <div class="send-email__file-input form-group">
                <label for="file" class="image-upload-button btn  btn-light border-secondary">
                    Прикрепить файл
                    <input type="file" name="file" class="form-control-file" title="" id="id_file">
                </label>
                <span class="send-email__filename-container text-dark ml-4"></span>
            </div>

            <div class="text-center">
                <button class="btn btn-primary" type="submit">{% trans 'Send' %}</button>
            </div>
        </form>
    </div>
</section>

<script>
const fileInput = document.querySelector('.send-email__file-input input[name=file]')
const fileNameContainer = document.querySelector('.send-email__filename-container')
fileInput.addEventListener('change', () => { fileNameContainer.innerText = fileInput.value})
</script>

<script>
const submitButton = document.querySelector('button[type="submit"]')

const nameInput = document.querySelector('#name')
const messagelnput = document.querySelector('#id_message')
const emailInput = document.querySelector('#email')

function checkButtonActivity() {
  const inputAllFilled = nameInput.value && emailInput.value && messagelnput.value

  if (inputAllFilled) {
    submitButton.removeAttribute("disabled")
  } else {
    submitButton.setAttribute("disabled", "true")
  }
}

checkButtonActivity()

for (const input of [nameInput, messagelnput, emailInput]) {
  input.addEventListener('input', checkButtonActivity)
}
</script>

<style>
.send-email__file-input label {
    position: relative;
    overflow: hidden;
}

.send-email__filename-container {

}

.send-email__file-input input {
    width: 1000%;
    position: absolute;
    top: 0;
    right: 0;
    margin: 0;
    padding: 0;
    font-size: 20px;
    cursor: pointer;
    opacity: 0;
}
</style>
{% endblock content %}

pages/templates/support-research.html
{% extends '_base.html' %}
{% load i18n %}

{% block head %}
<title>Longevity InTime - {% trans 'Support research' %}</title>
{% endblock head %}

{% block content %}
<section class="main about container-fluid d-flex align-items-center">
    <div class="container justify-content-center my-4 py-4">
        <div class="mb-4 py-4 row px-lg-5 mx-lg-5">
            <div class="col-12 col-lg-3 text-left pt-2 mb-4">
                <a href="{% url 'pages:about' %}">
                    {% include 'includes/back-button.html' %}
                </a>
            </div>

            <h4 class="col text-uppercase section-heading text-dark text-center">
                {% if LANGUAGE_CODE == 'en' %}        
                    Support fundamental research in the fight against aging
                {% endif %}

                {% if LANGUAGE_CODE == 'ru' %}
                    Поддержите фундаментальные исследования по борьбе со старением
                {% endif %}
            </h4>

            <div class="col-12 col-lg-3 text-right mt-4 mt-lg-0"></div>
        </div>

        <section class="text-left text-secondary mb-2 pb-2 px-lg-5 mx-lg-5">
            {% if LANGUAGE_CODE == 'en' %}
                <p>Longevity InTime BioTech calls for helping the scientific communities of all countries in the world related to aging research, whose goal is to significantly extend life (120+).</p>
                <p>The paradox is that the average cost of research can be no more than the cost of an apartment in the center of the European capital, however, thousands of apartments are bought daily, but it takes 0 to spend on aging research that could extend the lives of apartment buyers themselves.</p>
                <p>Here are some studies that require investment. We will replenish this list. You can contact the authors of the research groups directly or <a href="{% url 'pages:send_email' %}?get_parameter_name={{ 'Supporting of fundamental research' }}">by emailing us</a>.
                <ol>
                    <li>Analysis of many scientific publications on the topic of cell aging has led experts to conclude that it is closely associated with translation impairments. (Recall that translation is the process of protein synthesis by a matrix from RNA, which, in turn, is copied from DNA). However, the mechanisms of this relationship have not yet been clarified.</li>
                    <li>The older a person is, the more divisions his cells have gone through and the more errors have accumulated in their DNA. Therefore, the number of defective proteins also increases with age. Is this process one of the aging mechanisms? How exactly does it lead to the transformation of a cell into a more "older" one? Is it possible to slow down or even stop this "accumulation of errors"? This is a little-studied question.</li>
                    <li>So, in a number of studies it was shown that blocking individual stages of translation or the intracellular signaling pathways that trigger it prolongs the life of a wide variety of organisms, from yeast to mammals. This gives hope that someday in the near future protein synthesis modulators will appear that will have the necessary selectivity and help humanity to prolong an active and healthy period of life without any side effects.</li>
                    <li>Studies of the CD36 gene - "the main age gene".</li>
                </ol>
            {% endif %}

            {% if LANGUAGE_CODE == 'ru' %}
                <p>Компания Longevity InTime BioTech призывает помогать научным сообществам любых стран мира, связанных с исследованиями старения, целью которых является значительное продление жизни (120+).</p>
                <p>Парадокс в том, что средняя стоимость исследования может составлять не более стоимости квартиры в центре европейской столицы, однако ежедневно покупаются тысячи квартир, но на исследования по старению, которые могли бы продлить жизни самим покупателям квартир, тратится 0.</p>
                <p>Вот некоторые исследования, которые требуют инвестиций. Мы будем пополнять данный список. Вы можете связаться с авторами исследовательских групп напрямую или <a href="{% url 'pages:send_email' %}?get_parameter_name={{ 'Поддержка фундаментальных исследований' }}" >написав нам на почту</a>.
                <ol>
                    <li>Анализ множества научных публикаций по теме старения клетки привёл экспертов к выводу, что оно тесно связано с нарушениями трансляции. (Напомним, что трансляцией называется процесс синтеза белка по матрице из РНК, которая, в свою очередь, скопирована с ДНК). Однако механизмы этой взаимосвязи до сих пор не выяснены.</li>
                    <li>Чем старше человек, тем больше делений прошли его клетки и тем больше ошибок накопилось в их ДНК. Поэтому количество дефектных белков с возрастом тоже увеличивается. Является ли этот процесс один из механизмов старения? Как именно он приводит к превращению клетки в более "пожилую"? Можно ли замедлить или даже остановить это "накопление ошибок"? Это малоизученный вопрос.</li>
                    <li>Так, в ряде исследований было показано, что блокирование отдельных этапов трансляции или запускающих её внутриклеточных сигнальных путей продлевает жизнь самых разных организмов, от дрожжей до млекопитающих. Это даёт надежду, что когда-нибудь в недалёком будущем появятся модуляторы белкового синтеза, которые будут обладать нужной избирательностью и помогут человечеству без каких-либо побочных эффектов продлить активный и здоровый период жизни.</li>
                    <li>Исследования гена CD36 -"главного по старению".</li>
                </ol>
            {% endif %}
        </section>
    </div>
</section>
{% endblock %}

pages/templates/team.html
{% extends '_base.html' %}
{% load i18n %}

{% block head %}
<title>Longevity InTime - {% trans 'Vacancies' %}</title>
{% endblock head %}

{% block content %}
<section class="main about container-fluid d-flex align-items-center">
    <div class="container justify-content-center mt-4">
        <section class="my-4">
            <a href={% url 'pages:about' %}>
                {% include 'includes/back-button.html' %}
                <span class="mx-4">{% trans 'About' %}</span>
            </a>
        </section>
        
        <h1 class="text-uppercase section-heading text-dark text-center mb-4 py-4">
            {% trans 'Our team' %}
        </h1>
        
        <section class="mb-4 pb-4 text-secondary">
            {% if LANGUAGE_CODE == 'en' %}
            <p>Longevity InTime BioTech team:</p>
            
            {% endif %}

            {% if LANGUAGE_CODE == 'ru' %}
            <p>Команда Longevity InTime BioTech:</p>

            {% endif %}
        </section>

        <section class="my-4 pb-4">
            <a href={% url 'pages:about' %}>
                {% include 'includes/back-button.html' %}
                <span class="mx-4">{% trans 'About' %}</span>
            </a>
        </section>
    </div>
</section>
{% endblock %}