api/urls.py
from django.urls import path, re_path, include
from .views import *

app_name = 'v1'

urlpatterns = [
    path('isemailexist/', IsEmailExist.as_view()),
    path('profile/', UserProfile.as_view()),
    path('dashboard/', UserDashboard.as_view()),
    path('data-history/', HealthDataHistoryAPIView.as_view()),
    path('signup/', UserSignUp.as_view(), name='signup'),
    path('token/', MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', MyTokenRefreshView.as_view(), name='token_refresh'),
    path('password/reset/', PasswordResetView.as_view(), name='rest_password_reset'),
    path('password/reset/confirm/', PasswordResetConfirmView.as_view(), name='rest_password_reset_confirm'),
    path('password/change/', PasswordChangeView.as_view(), name='rest_password_change'),
    path('policy/', policy),
    path('policy-intime/', PolicyIntime.as_view(), name='policy'),
    path('result/', Results.as_view(), name='result'),
    path('resultdata/', ResultsData.as_view(), name='resultdata'),
    path('countries/', countries_dict),
    path('genders/', genders_dict),
    path('getfirstresulttime/', getfirstresulttime),
    path('user_cardioactivity/create/', CreateUserCardioactivity.as_view()),
    path('user_cardioactivity/<int:start_date>/<int:end_date>/', UserCardioactivity.as_view()),
    path('recomendations/', UserRecomendations.as_view()),
    path('image/', Image.as_view(), name='image'),
    path('disease/', DiseaseViews.as_view()),
    path('cardio_recomendations/', CardioRecomendations.as_view()),
    path('user_profile/', ProfileUser.as_view()),
    path('med_card/', MedCard.as_view()),
    path('info/', InformationView.as_view(), name='info'),
    path('login/', include('rest_social_auth.urls_jwt_pair')),
    path('login/', include('rest_social_auth.urls_session')),
]

cms/urls.py
from django.urls import path

from .views import dashboard, result, DeleteDevice, delete_all_devices, recommendation, disease, \
    cardio_recommendation, parameters

app_name = 'cms'


urlpatterns = [
    path('dashboard/', dashboard, name='dashboard'),
    path('result/', result, name='result'),
    path('recommendation/', recommendation, name='recommendation'),
    path('delete-device/<uuid:pk>/', DeleteDevice.as_view(), name='delete_device'),
    path('delete-all-devices/', delete_all_devices, name='delete_all_devices'),
    path('disease/', disease, name='disease'),
    path('cardio_recommendation', cardio_recommendation, name='cardio_recommendation'),
    path('parameters/', parameters, name='parameters'),
]

users/urls.py
from django.urls import path, re_path, reverse_lazy
from django.contrib.auth import views as auth_views

from .views import activate_user_account, signup, profile, CustomLoginView, PasswordReset

# from users.views import validate_username

app_name = 'users'

urlpatterns = [
    re_path(r'activate/(?P<signed_user>[0-9A-Za-z_\-]+/[A-Za-z0-9_=-]+/[A-Za-z0-9_=-]+)/$',
            activate_user_account, name='activate_user_account'),
    path('signup/', signup, name='signup'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html',
                                                                   success_url=reverse_lazy('users:password_change_done')),
         name="password_change"),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='registration/password_changed.html'), name='password_change_done'),
    path('password_reset/', PasswordReset.as_view(success_url=reverse_lazy('users:password_reset_done')),
         name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/email_sent.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_confirm.html',
                                                                                success_url=reverse_lazy('users:password_reset_complete')),
         name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_confirmed.html'), name='password_reset_complete'),
    path('profile/', profile, name='profile'),
    #проверка существующего пользователя (почты )с использованием ajax
    # path('ajax/validate_email/', validate_email, name = 'validate_email'),
]

users/models.py
import uuid
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _

from .managers import CustomUserManager


# Create your models here.
class CustomUser(AbstractUser):

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    username = None
    image = models.ImageField(_('image'), blank=True, upload_to='images/')

    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)

    email = models.EmailField(_('email address'), unique=True)
    email_confirm = models.BooleanField(_('confirmed email'), default=False)
    is_doctor = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

users/forms.py
import copy
from pydoc import locate

from django import forms
from django.conf import settings
from django.contrib.auth import get_user_model, authenticate
from django.contrib.auth.forms import UsernameField
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.utils.translation import gettext_lazy as _
from django.utils.text import capfirst
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError
from social_core.backends.google import GoogleOAuth2

from cms.models import HealthData
from cms.converting import cm_to_feet


class CustomUserCreationForm(UserCreationForm):

    password1 = forms.CharField(
        label=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password', 'placeholder': _('Enter your password')}),
        strip=False,
        min_length=8,
        max_length=18,
    )
    password2 = forms.CharField(
        label=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password', 'placeholder': _('Repeat your password')}),
        strip=False,
    )

    use_required_attribute=False

    class Meta(UserCreationForm):
        model = get_user_model()
        fields = ('email',)


class CustomUserChangeForm(UserChangeForm):

    class Meta(UserChangeForm):
        model = get_user_model()
        fields = ('email', 'first_name', 'last_name', 'image')


class CustomAuthenticationForm(forms.Form):
    """
    Base class for authenticating users. Extend this to get a form that accepts
    username/password logins.
    """
    username = UsernameField(required=False, widget=forms.TextInput(attrs={'autofocus': True}))
    password = forms.CharField(
        required=False,
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password'}),
    )

    error_messages = {
        'invalid_login': _(
            "Please enter a correct email and password. Note that both "
            "fields may be case-sensitive."
        ),
        'inactive': _("This account is inactive."),
    }

    def __init__(self, request=None, *args, **kwargs):
        """
        The 'request' parameter is set for custom auth use by subclasses.
        The form data comes in via the standard 'data' kwarg.
        """
        self.request = request
        self.user_cache = None
        super().__init__(*args, **kwargs)

        # Set the max length and label for the "username" field.
        self.username_field = get_user_model()._meta.get_field(get_user_model().USERNAME_FIELD)
        username_max_length = self.username_field.max_length or 254
        self.fields['username'].max_length = username_max_length
        self.fields['username'].widget.attrs['maxlength'] = username_max_length
        if self.fields['username'].label is None:
            self.fields['username'].label = capfirst(self.username_field.verbose_name)

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        # https://stackoverflow.com/questions/547829/how-to-dynamically-load-a-python-class
        # Check if GoogleOAuth2 is added as Authentication Backend.
        if GoogleOAuth2 in [locate(BackEnd) for BackEnd in settings.AUTHENTICATION_BACKENDS]:

            # If previously signed up using google raise validation error.
            if username and get_user_model().objects.filter(
                    email=username,
                    social_auth__provider=GoogleOAuth2.name,
            ).exists():
                raise forms.ValidationError(
                    _("Please log in using your Google account."),
                    code='invalid'
                )

        if not username or not password:
            raise forms.ValidationError(
                self.error_messages['invalid_login'],
                code='invalid_login or password',
            )

        if username is not None and password:
            self.user_cache = authenticate(self.request, username=username, password=password)
            if self.user_cache is None:
                raise self.get_invalid_login_error()
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data

    def confirm_login_allowed(self, user):
        """
        Controls whether the given User may log in. This is a policy setting,
        independent of end-user authentication. This default behavior is to
        allow login by active users, and reject login by inactive users.
        If the given user cannot log in, this method should raise a
        ``forms.ValidationError``.
        If the given user may log in, this method should return None.
        """
        if not user.is_active:
            raise forms.ValidationError(
                self.error_messages['inactive'],
                code='inactive',
            )

    def get_user(self):
        return self.user_cache

    def get_invalid_login_error(self):
        msg = _('Invalid login or password')
        self.add_error('username', msg)
        self.add_error('password', msg)
        return forms.ValidationError(
            self.error_messages['invalid_login'],
            code='invalid_login',
            params={'username': self.username_field.verbose_name},
        )


class ProfileForm(forms.ModelForm):
    first_name = forms.CharField(min_length=2, max_length=30, validators=[RegexValidator(r'^[-a-zA-ZА-Яа-я]+\Z', message=_('Enter your name'))],
                                 help_text=None, error_messages={'required': _('Enter your name')})
    last_name = forms.CharField(min_length=2, max_length=150, validators=[RegexValidator(r'^[-a-zA-ZА-Яа-я]+\Z', message=_('Enter your last name'))],
                                help_text=None,  error_messages={'required': _('Enter your last name')})

    class Meta:
        model = get_user_model()
        fields = ('email', 'first_name', 'last_name')


class ImageForm(forms.ModelForm):
    class Meta:
        model= get_user_model()
        fields= ('image',)

class HealthDataForm(forms.ModelForm):
    MEASURING_SYSTEM = (
        (1, _('Metric')),
        (2, _('Inch'))
    )
    birth_date = forms.DateField(
        label=_('Birth date'),
        help_text=None,
        widget=forms.DateInput(format='%Y-%m-%d', attrs={'placeholder': _('birth date: format 26.10.2006'),
                                                         'type': 'date'
                                                         }))
    measuring_system = forms.ChoiceField(choices=MEASURING_SYSTEM, required=True, help_text=None, label=_('Measuring system'))

    height = forms.FloatField(help_text=None, initial=0, required=True, label=_('Height'),
                               widget=forms.TextInput(attrs={'placeholder': ''}))

    class Meta:
        model = HealthData
        fields = ('birth_date', 'country', 'gender', 'height', 'smoker', 'measuring_system')

    def get_initial_for_field(self, field, field_name):
        value = self.initial.get(field_name, field.initial)
        if field_name == 'height':
            field_name = 'measuring_system'
            unit = self.initial.get(field_name, field.initial)
            if unit == 2 and value:
                value = cm_to_feet(value)
                # value_ft = round(value // 30.48)
                # value_in = round((value / 30.48 - value // 30.48) * 12)
                # value = (float(str(value_ft) + "." + str(value_in)))
                # if value < 1.8:
                #     value = 1.8
                # if value > 8.7:
                #     value = 8.7
        return value

    def clean(self):
        cd = self.cleaned_data
        height = cd['height'] if 'height' in cd else None
        if int(cd['measuring_system']) == 2:
            if not height or height < 1.8 or height > 8.7:
                HealthDataForm.add_error(self, field='height', error=ValidationError(_('The value must be between 1.8 up to 8.7 ft')))
        else:
            if not height or height < 50 or height > 260:
                HealthDataForm.add_error(self, field='height', error=ValidationError(_('The value must be between 50 up to 260 cm')))

users/templates/email_verify_done.html
{% extends '_base.html' %}
{% load i18n %}

{% block head %}
<title>Longevity InTime - {% trans 'Email address confirmed' %}</title>
{% endblock head %}

{% block content %}
<section class="main email-verify-done container-fluid d-flex align-items-center">
    <div class="container transparent justify-content-center py-6 py-md-0 mx-auto px-lg-5">
        {% if user.is_active %}
            {% if reuqest.user.is_authenticated %}
            <a class="text-center" href="{% url 'user:profile' %}">Перейти в профиль</a>

            {% else %}
            <h3 class="text-center py-1 my-3">
                {% trans 'Your email address confirmed!' %}
                <br>
                {% trans 'You can' %}
                <a href="{% url 'users:login' %}" class="text-primary"> {% trans 'log in now' %}</a>
                {% trans 'or do it in your mobile app' %}
            </h3>
            {% endif %}
        {% else %}
        <p class="text-center">{% trans "Something went wrong." %}</p>
        {% endif %}
    </div>
</section>

<script>
setTimeout(() => {
    window.location.href = "{% url 'users:login' %}"
}, 10000)
</script>
{% endblock content %}

users/templates/email_verify_end_of_time.html
{% extends '_base.html' %}
{% load i18n %}

{% block head %}
<title>Longevity InTime - {% trans 'Verify your email' %}</title>
{% endblock head %}

{% block content %}
<section class="main email-verify-done container-fluid d-flex align-items-center">
    <div class="container justify-content-center py-4 py-md-0 mt-4">
        <h1 class="text-center">{% trans 'Confirm your email address.' %}</h1>
        <p>{% blocktrans %}This e-mail confirmation link expired or is invalid. We have sent you an email with a new link. Please check your mail.{% endblocktrans %}</p>
    </div>
</section>
{% endblock content %}

users/templates/preorder_done.html
{% extends '_base.html' %}
{% load i18n %}

{% block head %}
<title>Longevity InTime - {% trans 'Welcome' %}</title>
{% endblock head %}

{% block content %}
<section class="main preorder-done container-fluid d-flex align-items-center">
    <div class="container justify-content-center py-4 py-md-0 mt-4">
        <p class="text-secondary pt-4 text-center">
        {% trans 'Your preorder is done' %}
        </p>
    </div>
</section>
{% endblock content %}

users/templates/profile.html
{% extends '_base.html' %}
{% load i18n %}
{% load static %}
{% load bootstrap4 %}
{% block head %}

<title>Longevity InTime - {% trans 'Profile' %}</title>
<script src="https://cdn.jsdelivr.net/npm/vue@2.6.11"></script>

<link
  href="{% static '/components/image-upload/js/chunk-vendors.js' %}"
  rel="preload"
  as="script"
/>
<link
  href="{% static '/components/image-upload/js/app.js' %}"
  rel="preload"
  as="script"
/>
<link
  href="{% static '/components/image-upload/css/app.css' %}"
  rel="stylesheet"
/>
{% endblock head %}

{% block content %}
<section class="main profile container-fluid d-flex align-items-center">
  <div class="container justify-content-center py-4 py-md-0 mt-4 px-0">
    <h1 class="text-uppercase section-heading text-dark text-center my-4 py-4">
      {% trans 'Profile' %}
    </h1>

    <form
      class="profile-form text-secondary"
      enctype="multipart/form-data"
      action="{% url 'v1:image' %}"
    >
      {% csrf_token %}

      <div class="row justify-content-between text-secondary py-4 py-md-0 py-4 flex-wrap">
        <div class="col-12 col-md-auto px-md-3 pb-4 pb-md-0 text-center d-flex flex-column align-items-start justify-content-between">
          {% if user.image %}
          <div class="avatar mx-auto" style="background-image: url({{ user.image.url }});"></div>
          {% else %}
          <div class="avatar d-flex align-items-center justify-content-center text-uppercase mx-auto">
            <span id="no-photo">{% trans 'No photo' %}</span>
          </div>
          {% endif %}

          <label for="image" class="image-upload-button btn  btn-light border-secondary mt-4 mb-0">
            {% trans 'Upload photo' %}
            <input
              id="id_image"
              type="file"
              name="image"
              accept="image/*"
              class="form-control-file"
              title=""
            />
          </label>

          <div
            id="app"
            hidden
            rotatetext="{% trans 'Rotate' %}"
            savetext="{% trans 'Save' %}"
          ></div>
        </div>

        <div
          class="devices col-12 col-md text-secondary py-4 ml-md-4 mt-4 mt-md-0"
        >
          <div class="card-title text-uppercase text-center">
            <b>{% trans "Your devices" %}</b>
          </div>

          <div class="container">
            {% for device in user.device.all %}
            <div class="row align-items-center">
              <div class="col">{{ device.device_model }}</div>
              <div class="col text-right">
                <a
                  href="{% url 'cms:delete_device' device.pk %}"
                  class="btn btn-outline-danger px-3"
                  >{% trans "Delete" %}</a
                >
              </div>
            </div>
            {% empty %}
            <div class="my-4 text-center">
              {% trans "No registered devices" %}
            </div>
            {% endfor %}
          </div>

          {% if user.device.all %}
          <div class="text-center">
            <a
              href="{% url 'cms:delete_all_devices' %}"
              class="btn btn-outline-danger mt-4"
              >{% trans "Delete all devices" %}</a
            >
          </div>
          {% endif %}
        </div>
      </div>
    </form>
    <form
      class="profile-form text-secondary"
      method="post"
      enctype="multipart/form-data"
      action="{% url 'users:profile' %}"
      novalidate
    >
      {% csrf_token %}
      <div class="py-4">
        <div class="form-group row pt-4 mx-0">
          {% bootstrap_form_errors form_data layout='inline' %}

          <div class="col-8">
            <label for="id_email">{% trans 'Email address' %}</label>
            {% bootstrap_field form.email show_label=False %}
          </div>

          <div class="col-4 text-right d-flex align-items-end justify-content-end pb-3">
            <a
              class="btn  btn-light border-secondary"
              href="{% url 'users:password_change' %}">
              {% trans 'Change password' %}
            </a>
          </div>
        </div>

        <div class="row mx-0">
          <div class="form-group col-12 col-lg-6">
            <label for="id_first_name">{% trans 'First name' %}</label>
            {% bootstrap_field form.first_name show_label=False placeholder=''%}
          </div>

          <div class="form-group col-12 col-lg-6">
            <label for="id_last_name">{% trans 'Last name' %}</label>
            {% bootstrap_field form.last_name show_label=False placeholder='' %}
          </div>
        </div>

        <div class="card mx-0 mt-4 mb-0">
          <div class="row mx-0">
            <button
              class="col btn btn-secondry text-left text-secondary mx-0 font-weight-bold"
              type="button"
              data-toggle="collapse"
              data-target="#collapseOne"
              aria-expanded="true"
              aria-controls="collapseOne"
            >
              {% trans 'Additional data' %}
              <span id="collapseSign" class="font-weight-bold"></span>
            </button>
          </div>

          <div id="collapseOne" class="row mx-0 collapse mb-0 mt-3">
            <div class="form-group col">
              {% bootstrap_field form_data.birth_date %}

              {% bootstrap_field form_data.country %}

              <div class="row mx-0 align-items-start">
                <div class="col-6 p-0">
                  {% bootstrap_field form_data.gender %}
                </div>

                <div class="col-6 pl-3 mb-1 pr-0">
                  {% bootstrap_field form_data.smoker %}
                </div>
              </div>
            </div>

            <div class="form-group col">
              {% bootstrap_field form_data.height %}

              {% bootstrap_field form_data.measuring_system %}

              <div class="text-right mt-4 pt-4">
                <a href="{% url 'cms:disease' %}" class="btn btn-light border-secondary">
                  {% trans "Disease" %}
                </a>
              </div>
            </div>
          </div>
        </div>

        <div class="d-flex justify-content-between my-4">
          <button class="btn btn-danger" id="confirm" type="button">
            {% trans 'Delete profile' %}
          </button>
          <button class="btn btn-primary" type="submit">
            {% trans 'Save' %}
          </button>    
        </div>
      </div>
    </form>
  </div>

  <div class="modal" id="modal">
    <div class="modal-dialog" >
      <div class="modal-content">
        <div class="modal-header p-4">
          <h5 class="modal-title"> {% trans 'Deleting a Profile' %}</h5>
        </div>
        <div class="modal-body px-4">
            {% blocktrans %}Deleting your profile, you permanently lose all data on our website and in the mobile app. The operation is irreversible and you will no longer be able to log in to your account{% endblocktrans %}
        </div>
        <div class="modal-footer p-4">
          <button class="btn btn-danger" id="delete">
            {% trans 'Delete' %}
          </button>
          <button type="button" class="btn btn-primary" id="cancel">
            {% trans 'Cancel' %}
          </button>
        </div>
      </div>
    </div>
  </div>
</section>

<script
  type="text/javascript"
  src="{% static '/components/image-upload/js/chunk-vendors.js' %}"
></script>

<script
  type="text/javascript"
  src="{% static '/components/image-upload/js/app.js' %}"
></script>

<script>
// Open/close additional fields block
const collapseOne = document.querySelector('#collapseOne')
const collapseSign = document.querySelector('#collapseSign')
const collapseButton = document.querySelector('[data-toggle="collapse"]')

setSign()

$('#collapseOne').on('hidden.bs.collapse', function(e) {
  collapseSign.innerText = '+'
})

$('#collapseOne').on('show.bs.collapse', function(e) {
  collapseSign.innerText = '-'
})

function setSign() {
  if (collapseOne.classList.contains('show')) {
    collapseSign.innerText = '-'
  } else {
    collapseSign.innerText = '+'
  }
}
</script>

<script>
/// Recalculate height value on measuring system change
var RESULT;
$(document).ready(function() {
  RESULT = $("#id_height").val();
});
$("#id_height").change(function() {
  RESULT = $("#id_height").val();
});
$( "#id_measuring_system" ).change(function() {
  let inch, flag;
  let firstPart, secondPart = "";
  if ($("#id_measuring_system").val() == 1){
    flag = RESULT.indexOf(",");
    RESULT = Number(RESULT.slice(0, flag) * 30.48) + Number(RESULT.slice(flag + 1, flag + 9) * 2.54);
    $("#id_height").val(Math.round(RESULT))
  } else {
    inch = (RESULT % 30.48) / 2.54;
    $("#id_height").val(Math.floor(RESULT / 30.48) + "," + Math.round(inch))
    RESULT = Math.floor(RESULT / 30.48) + "," + inch;
  }
});
</script>

<script>
  const confirmBtn = document.getElementById("confirm");
  const modal = document.getElementById("modal");
  const cancelBtn = document.getElementById("cancel");
  const deleteBtn = document.getElementById("delete");

  function getCookie(name) {
    var matches = document.cookie.match(new RegExp("(?:^|; )" + name.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g, '\\$1') + "=([^;]*)"));
    return matches ? decodeURIComponent(matches[1]) : undefined;
  }

  async function deleteProfile() {
    const params = {
        method : "GET",
        headers: {
            "Content-Type": "application/json;charset=utf-8",
            "X-CSRFToken": getCookie("csrftoken"),
            "sessionid": getCookie("sessionid"),
            "Access-Control-Allow-Origin": "*"
        }
    }
    let res = await fetch('/api/v2/profile', params , {})
    if (res.ok) {
      window.location.href = '/'
    }
    return await res.json()
  }

  confirmBtn.addEventListener("click", () => {
    modal.classList.add("show")
    document.body.style.overflowY = "hidden"
  })

  cancelBtn.addEventListener("click", () => {
    modal.classList.remove("show")
    document.body.style.overflowY = "auto"
  })

  deleteBtn.addEventListener("click", async () => {
    try {
      let res = await deleteProfile()
    } catch (error) {
      alert(error)
    }
  })
</script>


<style>
  small.form-text {
    display: none;
  }

  #collapseSign {
    float: right;
  }

  .modal {
    display: flex;
    justify-content: center;
    align-items: center;
    background-color: rgba(0, 0, 0, 0.336);
    opacity: 0;
    transition: opacity .3s;
    pointer-events: none;
  }

  .modal-content {
    border-radius: 20px;  
  }
  .modal.show {
    opacity: 1;
    pointer-events: all;
  }

  .modal-dialog {
    width: 100%;
  }

  .modal-footer {
    display: flex;
    justify-content: space-between;
  }

  .modal-header, .modal-footer {
    border: none;
  }
  .modal-footer .delete-form {
    width: auto;
    margin: 0;
  }
</style>
{% endblock content %}

users/templates/user_does_not_exist.html
{% extends '_base.html' %}
{% load i18n %}

{% block head %}
<title>Longevity InTime - {% trans 'User`s verification' %}</title>
{% endblock head %}

{% block content %}
<section class="main user_does_not_exist container-fluid d-flex align-items-center">
    <div class="container justify-content-center py-4 py-md-0 mt-4">
        <h1 class="text-center">{% trans "User does not exist" %}</h1>
        <p>
            {% blocktrans %}User does not exist. We checked our database and unfortunately did not find you in it.Please go through the {% endblocktrans %}
            <a href="{% url 'users:signup' %}">{% trans 'registration process' %}</a>.
            {% trans 'Or contact with our' %}
            <a href="mailto:support@intime.digital">
            {% trans 'customer service' %}
            </a>
        </p>
    </div>

{% endblock content %}