api/urls.py
from django.urls import path, re_path, include
from .views import *

app_name = 'v1'

urlpatterns = [
    path('isemailexist/', IsEmailExist.as_view()),
    path('profile/', UserProfile.as_view()),
    path('dashboard/', UserDashboard.as_view()),
    path('data-history/', HealthDataHistoryAPIView.as_view()),
    path('signup/', UserSignUp.as_view(), name='signup'),
    path('token/', MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', MyTokenRefreshView.as_view(), name='token_refresh'),
    path('password/reset/', PasswordResetView.as_view(), name='rest_password_reset'),
    path('password/reset/confirm/', PasswordResetConfirmView.as_view(), name='rest_password_reset_confirm'),
    path('password/change/', PasswordChangeView.as_view(), name='rest_password_change'),
    path('policy/', policy),
    path('policy-intime/', PolicyIntime.as_view(), name='policy'),
    path('result/', Results.as_view(), name='result'),
    path('resultdata/', ResultsData.as_view(), name='resultdata'),
    path('countries/', countries_dict),
    path('genders/', genders_dict),
    path('getfirstresulttime/', getfirstresulttime),
    path('user_cardioactivity/create/', CreateUserCardioactivity.as_view()),
    path('user_cardioactivity/<int:start_date>/<int:end_date>/', UserCardioactivity.as_view()),
    path('recomendations/', UserRecomendations.as_view()),
    path('image/', Image.as_view(), name='image'),
    path('disease/', DiseaseViews.as_view()),
    path('cardio_recomendations/', CardioRecomendations.as_view()),
    path('user_profile/', ProfileUser.as_view()),
    path('med_card/', MedCard.as_view()),
    path('info/', InformationView.as_view(), name='info'),
    path('login/', include('rest_social_auth.urls_jwt_pair')),
    path('login/', include('rest_social_auth.urls_session')),
]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name='index'),
    path('privacy/', views.privacy, name='privacy'),
    path('terms/', views.terms, name='terms'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('application/', views.application, name='application'),
    path('antivirus/', views.antivirus, name='antivirus'),
    path('company-mission/', views.companyMission, name='company-mission'),
    path('investor-relations/', views.investorRelations, name='investor-relations'),
    path('doctor-relations/', views.doctorRelations, name='doctor-relations'),
    path('vacancies/', views.vacancies, name='vacancies'),
    path('support-research/', views.supportResearch, name='support-research'),
    path('articles/', views.articles, name='articles'),
    path('additional/', views.additional, name='additional'),
    path('articles/<slug:pubmed_id>/', views.article_detail, name='article_detail'),
    path('send-email/', views.send_email, name='send_email'),
]

pages/templates/includes/chat-bot.html
{% load i18n %}
{% load static %}

<script src="https://www.gstatic.com/dialogflow-console/fast/messenger/bootstrap.js?v=1"></script>
<df-messenger
  intent=""
  chat-icon={% static 'img/messenger.png' %}
  chat-title="InTime-bot"
  agent-id="eda4e55d-6ab9-4c36-aa7a-5c173552e0c4"
  language-code={{ LANGUAGE_CODE }}>
</df-messenger>

<style style="css">
  df-messenger {
   --df-messenger-bot-message: #878fac;
   --df-messenger-button-titlebar-color: #052b45;
   --df-messenger-chat-background-color: #fafafa;
   --df-messenger-font-color: white;
   --df-messenger-send-icon: #878fac;
   --df-messenger-user-message: #479b3d;
  }
</style>

pages/templates/includes/download-mobile-apps.html
{% load i18n %}
{% load static %}

<div class="d-flex jusify-content-center">
  <a href="#" data-toggle="modal" role="button" data-target="#downloadAppsModal" class="btn action-btn mx-auto my-4 px-3 py-2 text-uppercase shadow">
    <div class="text-secondary">{% trans 'Download mobile apps' %}</div>
    <div class="font-weight-bold" style="color: #1AB2FD;">iOS & Android</div>
  </a>
</div>

<!--  Modal windows -->
<div id="downloadAppsModal" class="modal hide fade in px-0" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content bg-light">
            <div class="modal-header">
                <button type="button" class="close text-secondary" data-dismiss="modal" aria-hidden="true">{% include 'includes/close-button.html' %}</button>
            </div>

            <div class="modal-body text-dark text-center pt-0">
              {% if LANGUAGE_CODE == 'en' %}
              This is test version. Hope for your understanding. In case some bugs, please report on <a href="{% url 'pages:send_email' %}?get_parameter_name={{ 'Bug report' }}" target="_blank">support@intime.digital</a>
              {% endif %}

              {% if LANGUAGE_CODE == 'ru' %}
                Это тестовая версия. Надеемся на понимание о наличии возможных ошибок. Будем благодарны за обратную связь на
                <a href="{% url 'pages:send_email' %}?get_parameter_name={{ 'Bug report' }}" target="_blank">support@intime.digital</a>
              {% endif %}
            </div>

            <div class="text-center pb-4">
              <a href="https://play.google.com/store/apps/details?id=com.application.bmiobesity" target="_blank" role="button" class="btn action-btn shadow my-4 px-3 py-2 mx-3">
                <div class="text-secondary">{% trans 'Download for Android' %}</div>
                <div class="text-dark font-weight-bold">BMI Disease Tracker</div>
              </a>

              <a href="https://apps.apple.com/ru/app/antiobesity/id1511198472" target="_blank" role="button" class="btn action-btn shadow my-4 px-3 py-2 mx-3">
                <div class="text-secondary">{% trans 'Download for iOS' %}</div>
                <div class="text-dark font-weight-bold">AntiObesity</div>
              </a>

              <a target="_blank" role="button" data-toggle="modal" data-target="#downloadInstructionModal" class="btn action-btn shadow my-4 px-3 py-2 mx-3">
                <div class="text-secondary">{% trans 'Download for Android' %}</div>
                <div class="text-dark font-weight-bold">AntiCoronaVirus</div>
              </a>
            </div>
        </div>
    </div>
</div>

<div id="downloadInstructionModal" class="modal hide fade in px-0" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered modal-lg shadow">
        <div class="modal-content bg-light">
            <div class="modal-header">
                <button type="button" class="close text-secondary" data-dismiss="modal" aria-hidden="true">{% include 'includes/close-button.html' %}</button>
            </div>

            <div class="modal-body text-dark pt-0 text-center">
              {% if LANGUAGE_CODE == 'en' %}
                <p class="text-center px-4">
                  Thank you for downloading our <span class="font-weight-bold">Anti Corona Virus</span> app.
                </p>

                <div class="text-justify px-4">
                  We apologize for the lack of this application on Google Play.
                  This is Google's policy and we are committed to addressing this temporary inconvenience as soon as possible.
                  Please watch this video.
                  It provides step-by-step instructions for installing the application from the file you downloaded.
                </div>
              {% endif %}

              {% if LANGUAGE_CODE == 'ru' %}
                <p class="text-center px-4">
                  Благодарим Вас за скачивание нашего приложения <span class="font-weight-bold">Anti Corona Virus</span>.
                </p>

                <div class="text-justify px-4">
                  Приносим свои извинения за отсутствие данного приложения в Google Play.
                  Это связано с политикой Google и мы стремимся как можно скорее устранить это временное неудобство.
                  Пожалуйста, посмотрите данное видео.
                  В нем представлена пошаговая инструкция по установке приложения со скачаного Вами файла.
                </div>
              {% endif %}

              <div class="my-4 text-center col video-container">
                <video controls width="100%" height="300">
                  <source src="{% static '/android/AntiVirusApp-video-instruction.webm' %}" type="video/webm">
                  {% trans "Sorry, but your browser doesn't support HTML5 video." %}
                </video>
              </div>

              <a href={% static '/android/AntiVirusApp-release version-0.5.8.apk' %} target="_blank" role="button" class="btn action-btn shadow my-4 px-3 py-2 mx-3">
                <div class="text-secondary">{% trans 'Download for Android' %}</div>
                <div class="text-dark font-weight-bold">AntiCoronaVirus</div>
              </a>
            </div>
        </div>
    </div>
</div>

<style>
  .modal-dialog .bg-light {
    background: rgba(255, 255, 255, 0.7);
    backdrop-filter: blur(5px);
    font-family: 'Montserrat', Arial, Helvetica, Verdana, sans-serif;
  }

  .modal-dialog .bg-light * {
    animation: nav-icons 0s forwards !important;
  }

  .modal-dialog .bg-light div {
    border: none;
  }

  .modal-content {
      border-radius: 20px;
  }

  #downloadInstructionModal .modal-dialog {
    max-width: 585px;
  }
</style>

pages/templates/includes/landing-links.html
{% load i18n %}
{% load static %}

{% if LANGUAGE_CODE == 'en' %}
<div class="articles p-2">
  <h5 class="d-none d-md-block text-secondary">Articles</h5>
  &#9679;

  <a
    class="font-weight-normal"
    target="_blank"
    href="https://www.longevity.technology/real-time-tracking-of-400-longevity-biomarkers/">
    Longevity technology
  </a>
</div>

<div class="interviews mt-md-2 p-2">
  <h5 class="d-none d-md-block text-secondary">Interviews</h5>

  <div>
    &#9679;

    <a
      class="font-weight-normal"
      target="_blank"
      href="https://www.linkedin.com/posts/olegteterin_3q-racefields-bigdata-activity-6711997044938084352-MGfr">
      David Gammond Podcast
    </a>
  </div>

  <div>
    &#9679;

    <a
      class="font-weight-normal"
      target="_blank"
      href="https://www.linkedin.com/posts/olegteterin_the-leadership-in-business-podcast-episode-activity-6709868738478391296-sgRQ">
      The Leadership In Business Podcast
    </a>
  </div>
</div>

<div class="awards mt-md-2 p-2">
  <h5 class="d-none d-md-block text-secondary">Awards</h5>

  &#9679;
  <a
    class="font-weight-normal"
    target="_blank"
    href="https://www.linkedin.com/posts/olegteterin_longevity-intime-biotech-llc-the-usa-2020-activity-6745037922069733376-c5H_">
    International Life Sciences Award
  </a>
</div>
{% endif %}

{% if LANGUAGE_CODE == 'ru' %}
<div class="interviews p-2">
  <h5 class="d-none d-md-block text-secondary">Статьи</h5>
  &#9679;

  <a
    class="font-weight-normal"
    target="_blank"
    href="https://www.longevity.technology/real-time-tracking-of-400-longevity-biomarkers/">
    Longevity technology
  </a>
</div>

<div class="interviews mt-md-2 p-2">
  <h5 class="d-none d-md-block text-secondary">Интервью</h5>

  <div>
    &#9679;

    <a
      class="font-weight-normal"
      target="_blank"
      href="https://www.linkedin.com/posts/olegteterin_3q-racefields-bigdata-activity-6711997044938084352-MGfr">
      David Gammond Podcast
    </a>
  </div>

  <div>
    &#9679;

    <a
      class="font-weight-normal"
      target="_blank"
      href="https://www.linkedin.com/posts/olegteterin_the-leadership-in-business-podcast-episode-activity-6709868738478391296-sgRQ">
      The Leadership In Business Podcast
    </a>
  </div>
</div>

<div class="awards mt-md-2 p-2">
  <h5 class="d-none d-md-block text-secondary">Награды</h5>

  &#9679;
  <a
    class="font-weight-normal"
    target="_blank"
    href="https://www.linkedin.com/posts/olegteterin_longevity-intime-biotech-llc-the-usa-2020-activity-6745037922069733376-c5H_">
    International Life Sciences Award
  </a>
</div>
{% endif %}

<style>
.articles, .awards, .interviews {
  width: fit-content;
  background-color: rgba(255, 255, 255, 0.8)
}
</style>

pages/templates/includes/preorder-button.html
{% load i18n %}

<a href={% url 'pages:application' %} role="button" class="preorder-button btn action-btn mx-auto my-4 px-3 py-2 text-uppercase shadow">
  {% if LANGUAGE_CODE == 'en' %}
    <div class="text-secondary font-weight-normal">Pre order</div>
    <div class="text-dark font-weight-bold">Full version</div>
  {% endif %}

  {% if LANGUAGE_CODE == 'ru' %}
    <div class="text-secondary font-weight-normal">Предзаказ</div>
    <div class="text-dark font-weight-bold">Полная версия</div>
  {% endif %}
</a>

pages/templates/includes/send-pitch-deck.html
{% load i18n %}
{% load static %}

{% if LANGUAGE_CODE == 'en' %}
    <a href="#" data-toggle="modal" data-target="#sendPitchDeckModal">send us your pitch deck</a> for fundraising options.
{% endif %}

{% if LANGUAGE_CODE == 'ru' %}
    <a href="#" data-toggle="modal" data-target="#sendPitchDeckModal">отправьте нам вашу презентацию</a> и мы рассмотрим возможность инвестиций.
{% endif %}

<!--  Modal windows -->
<div id="sendPitchDeckModal" class="modal hide fade in" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content bg-light--transparent">
          <div class="modal-header">
            <button type="button" class="close text-secondary" data-dismiss="modal" aria-hidden="true">{% include 'includes/close-button.html' %}</button>
          </div>

          <div class="modal-body text-dark pb-2 pb-md-4 mb-2 mb-md-4 px-4 mx-4">
            {% if LANGUAGE_CODE == 'en' %}
              <p class="text-left">
                As part of your registration process, applicants are required to share the status of their registration through social media with the following caption. E.g.

                <blockquote class="blockquote">
                  Our team just applied to @LongevityInTime #InvestInLongevity #LongevityInTime www.intime.digital
                </blockquote>

                The registration is confirmed once the LongevityInTime Twitter Account or Facebook post "Liked" your post or Tweet.
              </p>

              <div id="checkList" class="input-group mb-3">
                <div class="input-group-prepend">
                  <input class="form-check-input" type="checkbox" value="" id="check1">
                  <label class="form-check-label" for="check1">
                    I understand that in order for my application to be considered I must tweet
                  </label>
                </div>

                <div class="input-group-prepend">
                  <input class="form-check-input" type="checkbox" value="" id="check2">
                  <label class="form-check-label" for="check2">
                    I have read and agreed to the <a href="{% url 'pages:terms' %}" target="_blank">terms and conditions<a>
                  </label>
                </div>
              </div>

              <div class="text-center mt-4 pt-4 mb-0 pb-0">
                <a id="sendButton" href="{% url 'pages:send_email' %}?get_parameter_name={{ 'Investor relations' }}" class="btn btn-secondary border-secondary disabled" >Send pitch deck</a>
              </div>
            {% endif %}

            {% if LANGUAGE_CODE == 'ru' %}
              <p>
                В рамках вашего процесса регистрации кандидаты должны сообщить о статусе своей регистрации через социальные сети со следующей подписью. Например:

                <blockquote class="blockquote">
                  Наша команда только что подала заявку на @LongevityInTime #InvestInLongevity #LongevityInTime www.intime.digital
                </blockquote>

                <span>Регистрация подтверждается после того, как учетная запись LongevityInTime в Твиттере или посте Facebook "лайкнет" ваш пост или твит.</span>
              </p>

              <div class="input-group mb-3">
                <div class="input-group-prepend">
                  <input class="form-check-input" type="checkbox" value="" id="check1">
                  <label class="form-check-label text-left" for="check1">
                    Я прочитал и согласен с <a href="{% url 'pages:terms' %}" target="_blank">условиями использования</a>
                  </label>
                </div>

                <div class="input-group-prepend">
                  <input class="form-check-input" type="checkbox" value="" id="check2">
                  <label class="form-check-label text-left" for="check2">
                    Я понимаю, что для рассмотрения моей заявки я должен написать в Твиттере
                  </label>
                </div>
              </div>

              <div class="text-center mt-4 pt-4 mb-0 pb-0">
                <a id="sendButton" href="{% url 'pages:send_email' %}?get_parameter_name={{ 'Investor relations' }}" class="btn btn-secondary border-secondary disabled" >Отправить презентацию</a>
              </div>
            {% endif %}
          </div>
        </div>
    </div>
</div>

<script>
const sendButton = document.querySelector('#sendButton')
const check1 = document.querySelector('#check1')
const check2 = document.querySelector('#check2')

function watchCheckList(event) {
  if (check1.checked && check2.checked) {
    sendButton.classList.remove('disabled')
    sendButton.classList.remove('btn-secondary')
    sendButton.classList.add('btn-light')
  } else if (!sendButton.classList.contains('disabled')) {
    sendButton.classList.add('disabled')

    if (!sendButton.classList.contains('btn-secondary')) {
      sendButton.classList.remove('btn-light')
      sendButton.classList.add('btn-secondary')
    }
  }
}

check1.addEventListener('change', event => watchCheckList(event))
check2.addEventListener('change', event => watchCheckList(event))
</script>

<style>
#sendPitchDeckModal {
  padding-right: 0 !important;
}

.modal-dialog .bg-light--transparent {
  background: rgba(255, 255, 255, 0.8);
  backdrop-filter: blur(5px);
  border: solid 1px rgba(0, 0, 0, 0.2);

  font-family: 'Montserrat', Arial, Helvetica, Verdana, sans-serif;
}

.modal-dialog .bg-light--transparent * {
  animation: nav-icons 0s forwards !important;
}

.modal-dialog .bg-light--transparent div {
  border: none;
}
</style>