api/urls.py
from django.urls import path, re_path, include
from .views import *

app_name = 'v1'

urlpatterns = [
    path('isemailexist/', IsEmailExist.as_view()),
    path('profile/', UserProfile.as_view()),
    path('dashboard/', UserDashboard.as_view()),
    path('data-history/', HealthDataHistoryAPIView.as_view()),
    path('signup/', UserSignUp.as_view(), name='signup'),
    path('token/', MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', MyTokenRefreshView.as_view(), name='token_refresh'),
    path('password/reset/', PasswordResetView.as_view(), name='rest_password_reset'),
    path('password/reset/confirm/', PasswordResetConfirmView.as_view(), name='rest_password_reset_confirm'),
    path('password/change/', PasswordChangeView.as_view(), name='rest_password_change'),
    path('policy/', policy),
    path('policy-intime/', PolicyIntime.as_view(), name='policy'),
    path('result/', Results.as_view(), name='result'),
    path('resultdata/', ResultsData.as_view(), name='resultdata'),
    path('countries/', countries_dict),
    path('genders/', genders_dict),
    path('getfirstresulttime/', getfirstresulttime),
    path('user_cardioactivity/create/', CreateUserCardioactivity.as_view()),
    path('user_cardioactivity/<int:start_date>/<int:end_date>/', UserCardioactivity.as_view()),
    path('recomendations/', UserRecomendations.as_view()),
    path('image/', Image.as_view(), name='image'),
    path('disease/', DiseaseViews.as_view()),
    path('cardio_recomendations/', CardioRecomendations.as_view()),
    path('user_profile/', ProfileUser.as_view()),
    path('med_card/', MedCard.as_view()),
    path('info/', InformationView.as_view(), name='info'),
    path('login/', include('rest_social_auth.urls_jwt_pair')),
    path('login/', include('rest_social_auth.urls_session')),
]

cms/urls.py
from django.urls import path

from .views import dashboard, result, DeleteDevice, delete_all_devices, recommendation, disease, \
    cardio_recommendation, parameters

app_name = 'cms'


urlpatterns = [
    path('dashboard/', dashboard, name='dashboard'),
    path('result/', result, name='result'),
    path('recommendation/', recommendation, name='recommendation'),
    path('delete-device/<uuid:pk>/', DeleteDevice.as_view(), name='delete_device'),
    path('delete-all-devices/', delete_all_devices, name='delete_all_devices'),
    path('disease/', disease, name='disease'),
    path('cardio_recommendation', cardio_recommendation, name='cardio_recommendation'),
    path('parameters/', parameters, name='parameters'),
]

users/urls.py
from django.urls import path, re_path, reverse_lazy
from django.contrib.auth import views as auth_views

from .views import activate_user_account, signup, profile, CustomLoginView, PasswordReset

# from users.views import validate_username

app_name = 'users'

urlpatterns = [
    re_path(r'activate/(?P<signed_user>[0-9A-Za-z_\-]+/[A-Za-z0-9_=-]+/[A-Za-z0-9_=-]+)/$',
            activate_user_account, name='activate_user_account'),
    path('signup/', signup, name='signup'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html',
                                                                   success_url=reverse_lazy('users:password_change_done')),
         name="password_change"),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='registration/password_changed.html'), name='password_change_done'),
    path('password_reset/', PasswordReset.as_view(success_url=reverse_lazy('users:password_reset_done')),
         name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/email_sent.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_confirm.html',
                                                                                success_url=reverse_lazy('users:password_reset_complete')),
         name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_confirmed.html'), name='password_reset_complete'),
    path('profile/', profile, name='profile'),
    #проверка существующего пользователя (почты )с использованием ajax
    # path('ajax/validate_email/', validate_email, name = 'validate_email'),
]

cms/models.py
import json
from django.db import models
from datetime import date, timedelta
from django.core.exceptions import ValidationError
from django.forms import model_to_dict
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model
from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.serializers.json import DjangoJSONEncoder
from django.utils.translation import get_language

from .countries import COUNTRIES
from . import disease

User = get_user_model()


def validate_date(value):
    last_date = (date.today() - timedelta(days=47450))
    future_date = (date.today() - timedelta(days=3650))
    if not (last_date < value < future_date):
        raise ValidationError(_('Make sure the date is between {} and {}').format(last_date, future_date))


class JSONField(models.TextField):
    """
    JSONField is a generic textfield that neatly serializes/unserializes
    JSON objects seamlessly.
    example:
        class Page(models.Model):
            data = JSONField(blank=True, null=True)
        page = Page.objects.get(pk=5)
        page.data = {'title': 'test', 'type': 3}
        page.save()
    """
    def to_python(self, value):
        locale = get_language()
        if value == "":
            return None
        try:
            if isinstance(value, str):
                data = json.loads(value)
                data = data['ru'] if locale == 'ru' else data['en']
                return data
        except ValueError:
            pass
        return value

    def from_db_value(self, value, *args):
        return self.to_python(value)

    def get_db_prep_save(self, value, *args, **kwargs):
        if value == "":
            return None
        if isinstance(value, dict):
            value = json.dumps(value, cls=DjangoJSONEncoder)
        return value


class HealthDataAbstractModel(models.Model):
    MEASURING_SYSTEM = (
        (1, _('Metric')),
        (2, _('Inch'))
    )

    cholesterol = models.FloatField(
        null=True, blank=True,
        default=None, verbose_name=_('Cholesterol'),
        help_text=None
    )
    blood_pressure_sys = models.PositiveSmallIntegerField(
        null=True, blank=True,
        default=120, verbose_name=_('higher'),
        help_text=None
    )
    blood_pressure_dia = models.PositiveSmallIntegerField(
        null=True, blank=True,
        default=80, verbose_name=_('lower'),
        help_text=None
    )
    blood_saturation = models.PositiveSmallIntegerField(
        null=True, blank=True,
        default=0, verbose_name=_('higher'),
        help_text=None,
        validators=[MinValueValidator(30), MaxValueValidator(100)]
    )
    glucose = models.FloatField(
        null=True, blank=True,
        default=None, verbose_name=_('Glucose'),
        help_text=None
    )
    heart_rate_alone = models.PositiveSmallIntegerField(
        null=True, blank=True,
        default=60, verbose_name=_('heart rate'),
        help_text=None
    )
    weight = models.FloatField(
        null=True, blank=True,
        verbose_name=_('weight'),
        help_text=None, default=None
    )
    waist = models.FloatField(
        null=True, blank=True,
        verbose_name=_('waist'),
        help_text=None, default=None
    )
    wrist = models.FloatField(
        null=True, blank=True,
        verbose_name=_('wrist'),
        help_text=None, default=None
    )
    neck = models.FloatField(
        null=True, blank=True,
        default=None, verbose_name=_('neck'),
        help_text=None
    )
    hip = models.FloatField(
        null=True, blank=True,
        verbose_name=_('hip'), help_text=None,
        default=None
    )
    measuring_system = models.PositiveSmallIntegerField(
        choices=MEASURING_SYSTEM, default=1,
        verbose_name=_('Measuring system'),
        help_text=None
    )

    create = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True


class HealthData(HealthDataAbstractModel):
    GENDERS = (
        (1, _('Male')),
        (2, _('Female')),
    )
    ACTIVITY_LEVEL = (
       (1.2, _('Minimum')),
       (1.375, _('Lower')),
       (1.55, _('Medium')),
       (1.725, _('High')),
       (1.9, _('Very high')),
    )

    gender = models.PositiveSmallIntegerField(
        null=True, blank=True, choices=GENDERS, verbose_name=_('gender'), help_text=None,
        default=1, error_messages={'required': _('Select gender')}
    )
    birth_date = models.DateField(
        null=True, blank=True, validators=[validate_date], default='1990-01-01',
        verbose_name=_('Date of Birth'), help_text=None, error_messages={'required': _('Enter your date of birth')}
    )
    country = models.PositiveSmallIntegerField(
        null=True, blank=True, validators=[MinValueValidator(1, message=_('Choose a country Residence'))],
        choices=COUNTRIES, verbose_name=_('country'), help_text=None,
        error_messages={'required': _('Choose a country Residence')}, default=0
    )
    height = models.FloatField(null=True, blank=True, verbose_name=_('height'), help_text=None, default=None)
    smoker = models.BooleanField(null=True, blank=True, verbose_name=_('Smoker'), default=False)
    locale = models.CharField(blank=True, default='', max_length=8, help_text=None)

    user = models.OneToOneField(User, null=True, on_delete=models.SET_NULL, related_name='health_data')
    daily_activity_level = models.FloatField(
        null=True, blank=True, choices=ACTIVITY_LEVEL, default=1.55,
        verbose_name=_('Daily activity level'), help_text=None
    )
    update = models.DateTimeField(auto_now=True)

    # Fields that will be checked for changes and if changed then history is added
    relevant_fields = [
            'cholesterol', 'blood_pressure_sys', 'blood_pressure_dia',
            'blood_saturation', 'glucose', 'heart_rate_alone',
            'weight', 'waist', 'wrist', 'neck', 'hip'
            'measuring_system'
        ]

    def is_data_changed(self, previous_instance, new_instance):
        """
        :param previous_instance: Model Instance that has previous data
        :param new_instance: Model Instance that has new data
        :return: Boolean if data has been changed or not
        """
        previous_data = model_to_dict(
            previous_instance, fields=self.relevant_fields
        )
        new_data = model_to_dict(
            new_instance, fields=self.relevant_fields
        )
        return previous_data != new_data

    def make_history(self, previous_instance):
        """
        :param previous_instance: Instance that has previous data that will be added as history
        :return:
        """
        data = model_to_dict(
            previous_instance,
            fields=self.relevant_fields
        )
        HealthDataHistory.objects.create(
            health_data=self,
            **data
        )

    def save(self, **kwargs):
        # Only if data update
        if self.pk:
            previous_data_instance = HealthData.objects.get(id=self.pk)
            if self.is_data_changed(previous_data_instance, self):
                self.refresh_from_db()
                self.make_history(self)

            # Make history with previous data
            super().save(**kwargs)
        else:
            super().save(**kwargs)


class HealthDataHistory(HealthDataAbstractModel):
    health_data = models.ForeignKey(
        HealthData,
        on_delete=models.CASCADE,
        related_name='history'
    )


class CardioActivity(models.Model):
    health_model = models.ForeignKey(HealthData, on_delete=models.CASCADE, related_name='health_data')

    measuring_date = models.DateTimeField(auto_now_add=True)

    heart_rate_alone = models.PositiveSmallIntegerField(null=True, blank=True,
                                                        verbose_name=_('heart rate'),
                                                        help_text=None)
    blood_pressure_sys = models.PositiveSmallIntegerField(null=True, blank=True,
                                                          verbose_name=_('blood pressure systolic'),
                                                          help_text=None)
    blood_pressure_dia = models.PositiveSmallIntegerField(null=True, blank=True,
                                                          verbose_name=_('blood pressure diastolic'),
                                                          help_text=None)

    class Meta:
        ordering = ('-measuring_date',)


class Device(models.Model):
    device_uuid = models.UUIDField(primary_key=True, editable=True, unique=True)
    os_name = models.CharField(blank=True, default='', max_length=30)
    os_version = models.CharField(blank=True, default='', max_length=30)
    device_model = models.CharField(max_length=50, verbose_name=_('device model'))
    app_version = models.CharField(blank=True, max_length=30)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='device')
    token = models.TextField(blank=True, default='')


class Result(models.Model):
    dashboard = models.OneToOneField(HealthData, on_delete=models.CASCADE, related_name='result')
    bmi = models.FloatField(blank=True, null=True, verbose_name=_('Body mass index'), help_text=None)
    obesity_level = JSONField(blank=True, null=True, default='', verbose_name=_('Weight excess'), help_text=None)
    ideal_weight = models.FloatField(blank=True, null=True, verbose_name=_('Ideal weight'), help_text=None)
    base_metabolism = models.PositiveSmallIntegerField(null=True, blank=True, verbose_name=_('Basal metabolism'),
                                                       help_text=None)
    calories_to_low_weight = models.PositiveSmallIntegerField(null=True, blank=True, help_text=None,
                                                              verbose_name=_('Calories to low weight'))
    waist_to_hip_proportion = models.FloatField(null=True, blank=True, verbose_name=_('Waist-hip ratio'),

cms/templates/cms/cardio_recommendation.html
{% extends '_base.html' %}
{% load i18n %}
{% load bootstrap4 %}

{% block head %}
<title>Longevity InTime - {% trans 'Recommendations' %}</title>
{% endblock head %}
{% block content %}
<section class="main dashboard container-fluid d-flex align-items-center">
    <div class="container align-items-center mt-4">
        <section class="my-4">
            <a href="{% url 'cms:disease' %}">
                {% include 'includes/back-button.html' %}
                <span class="mx-4">{% trans 'Disease' %}</span>
            </a>
        </section>

        <section class="text-left text-secondary my-4 py-4 mx-lg-5 px-lg-5">
            <h1 class="text-uppercase section-heading text-dark text-center my-4 py-4">
                {% trans 'Recommendations' %}
            </h1>
            {% for r in rec %}
                <p class="card card-body">{{ r }}</p>
            {% endfor %}
        </section>
        {% if rec_not %}
        <section class="text-left text-secondary my-4 py-4 mx-lg-5 px-lg-5">
            <h1 class="text-uppercase section-heading text-dark text-center my-4 py-4">
                {% trans 'Not recommendations' %}
            </h1>

            {% for r in rec_not %}
                <p class="card card-body">{{ r }}</p>
            {% endfor %}
        </section>
        {% endif %}

        <section class="my-4 pb-4">
            <a href="{% url 'cms:disease' %}">
                {% include 'includes/back-button.html' %}
                <span class="mx-4">{% trans 'Disease' %}</span>
            </a>
        </section>
    </div>
</section>
{% endblock content %}

cms/templates/cms/dashboard.html
{% extends '_base.html' %}
{% load i18n %}
{% load bootstrap4 %}
{% load crispy_forms_tags %}

{% block head %}
    <title>Longevity InTime - {% trans 'Dashboard' %}</title>
{% endblock head %}

{% block content %}
<section class="main dashboard container-fluid d-flex align-items-center">
    <div class="container justify-content-center mt-4 pt-4 px-0 position-relative">
        <h1 class="text-uppercase section-heading text-dark text-center mb-4 py-4">
          {% trans 'Dashboard' %}
        </h1>

        <form method="post" class="text-secondary my-4 py-4">
            {% csrf_token %}

            <div class="row">
                <div class="col-12 col-lg-6">
                    <label>
                        <span>{{ form.weight.label }}</span>
                    </label>
                    {% bootstrap_field form.weight show_label=False %}
                    <small class="form-text text-muted mt-n3 mb-3">
                        {% if measuring_system == 1 %}
                                {% trans 'Weight in kg' %}
                        {% else %}
                            {% trans 'Weight in kg' %}
                        {% endif %}
                    </small>

                    <label>
                        <span>{{ form.hip.label }}</span>
                    </label>
                    {% bootstrap_field form.hip show_label=False%}
                    <small class="form-text text-muted mt-n3 mb-3">{% trans 'Thigh circumference in cm' %}</small>

                    <label>
                        <span>{{ form.waist.label }}</span>
                    </label>
                    {% bootstrap_field form.waist show_label=False%}
                    <small class="form-text text-muted mt-n3 mb-3">{% trans 'Waist circumference in cm' %}</small>

                    <label>
                        <span>{{ form.neck.label }}</span>
                    </label>
                    {% bootstrap_field form.neck show_label=False %}
                    <small class="form-text text-muted mt-n3 mb-3">{% trans 'Neck circumference in cm' %}</small>

                    <label>
                        <span>{{ form.wrist.label }}</span>
                    </label>
                    {% bootstrap_field form.wrist show_label=False %}
                    <small class="form-text text-muted mt-n3 mb-3">{% trans 'Wrist circumference at thinnest point in cm' %}</small>
                </div>

                <div class="col-12 col-lg-6">
                    <label>
                        {% trans 'Blood pressure' %}
                    </label>

                    <div class="row no-gutters">
                        <div class="col-5">
                            {% bootstrap_field form.blood_pressure_sys show_label=False %}
                        </div>

                        <div class="col-2 text-center py-2">/</div>

                        <div class="col-5">
                            {% bootstrap_field form.blood_pressure_dia  show_label=False %}
                        </div>

                        <small class="form-text text-muted mt-n3 mb-3">{% trans 'Systolic' %} / {% trans 'Diastolic pressure in mmHg Art.' %}</small>
                    </div>

                    <label>
                        {{ form.heart_rate_alone.label }}
                    </label>
                    {% bootstrap_field form.heart_rate_alone show_label=False %}
                    <small class="form-text text-muted mt-n3 mb-3">{% trans 'Pulse in beats per minute' %}</small>

                    <label>
                        {{ form.cholesterol.label }}
                    </label>
                    {% bootstrap_field form.cholesterol show_label=False %}
                    <small class="form-text text-muted mt-n3 mb-3">{% trans 'Blood cholesterol level in mmol/l' %}</small>

                    <label>
                        {{ form.glucose.label }}
                    </label>
                    {% bootstrap_field form.glucose show_label=False %}
                    <small class="form-text text-muted mt-n3 mb-3">{% trans 'Blood glucose level in mmol/l' %}</small>

                    <label>
                        {{ form.daily_activity_level.label }}
                    </label>
                    {% bootstrap_field form.daily_activity_level show_label=False %}
                    <small id="activityLevelHelpText" class="form-text text-muted mt-n3 mb-3">
                        {% if LANGUAGE_CODE == 'en' %}
                            <div class='text-left'></div>
                        {% endif %}

                        {% if LANGUAGE_CODE == 'ru' %}
                            <div class='text-left'></div>
                        {% endif %}
                    </small>
                </div>
            </div>

            <div class="text-center">
                <button class="btn btn-primary my-3" type="submit">{% trans 'Save' %}</button>
            </div>
        </form>


        {% if form_unfilled|length < 1 %}
          <div class="popup-message-container shadow rounded-lg bg-white">
            <div class="text-right">
              <button type="button" class="close text-secondary">
                {% include 'includes/close-button.html' %}
              </button>
            </div>

            <div class="p-3">
              <div class="popup-message text-center">
                {% trans 'Data saved.' %}
               </div>

              <a href={% url 'cms:parameters' %} class="text-primary">
                {% trans 'Open Parameters.' %}
              </a>

              <a href={% url 'cms:result' %} class="text-primary">
                {% trans 'Open Analisys.' %}
              </a>
            </div>
          </div>
        {% endif %}
    </div>
</section>

<script>
  // Popup message
  const popupMessageContainer = document.querySelector('.popup-message-container')
  const popupCloseButton = popupMessageContainer.querySelector('button')

  function closePopupMessage() {
    popupMessageContainer.setAttribute('hidden', 'true')
  }

  popupCloseButton.addEventListener('click', closePopupMessage)

  setTimeout(closePopupMessage, 5000)

  // Set and change select activity level help text
  const activityLevelHelpText = document.querySelector('#activityLevelHelpText')
  const activityLevelSelect = document.querySelector('#id_daily_activity_level')

  function updateDailyActivity(value) {
      const options = Array.from(document.querySelectorAll('#id_daily_activity_level option'))
      const helpText = [
          {% if LANGUAGE_CODE == 'en' %}
              "",
              "Passive lifestyle",
              "Light physical labor, walking",
              "Physical labor or training 3-5 times a week",
              "Heavy physical labor or training 6-7 times a week",
              "I unload wagons day and night"
          {% endif %}

          {% if LANGUAGE_CODE == 'ru' %}
              "",
              "Пассивный образ жизни",
              "Легкий физический труд, пешие прогулки",
              "Физический труд или тренировки 3-5 раз в неделю",
              "Тяжелый физический труд или тренировки 6-7 раз в неделю",
              "Разгружаю вагоны днем и ночью"
          {% endif %}
      ]

      options.forEach((option, index) => {
          if (value === option.value) {
              activityLevelHelpText.innerText = helpText[index]
          }
      })
  }

  window.addEventListener('load', () => updateDailyActivity(activityLevelSelect.value))
  activityLevelSelect.addEventListener('change', event => updateDailyActivity(event.target.value))
</script>

<script>
  // Switch save button activity based on form filling
  const saveButton = document.querySelector('button[type=submit')
  const inputList = document.querySelectorAll('.dashboard form input')

  for (const input of inputList) {
      input.addEventListener('input', checkIfFormFilled)
      input.addEventListener('input', closePopupMessage)
  }

  function checkIfFormFilled() {
      const unnecessaryInputs = ['glucose', 'cholesterol']

      const unfilledIntputs = Array.from(inputList)
          .filter(input => !input.value.length)
          .filter(input => !unnecessaryInputs.includes(input.name))

      if (unfilledIntputs.length === 0) {
          saveButton.removeAttribute('disabled')
      } else {
          saveButton.setAttribute('disabled', 'disabled')
      }
  }

  checkIfFormFilled()
</script>

<style>
  .dashboard form p,
  .dashboard form div,
  .dashboard form,
  .dashboard .form-control,
  .dashboard .form-group {
    max-width: 60rem;
  }
</style>
{% endblock content %}

cms/templates/cms/delete_all_devices.html
{% extends '_base.html' %}
{% load i18n %}

{% block title %}{% trans "delete device" %}{% endblock title %}

{% block content %}
<section class="main profile container-fluid d-flex align-items-center">
    <div class="container justify-content-center py-4 py-md-0 mt-4">
        <h2 class="text-center">{% trans "Are you sure delete all devices?" %}</h2>
        
        <div class="row">
            <form method="post" class="text-center">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-danger my-4">{% trans "Delete" %}</button>
            </form>
        </div>
    </div>
</section>
{% endblock content %}

cms/templates/cms/delete_device.html
{% extends '_base.html' %}
{% load i18n %}

{% block title %}{% trans "delete device" %}{% endblock title %}

{% block content %}
<section class="main profile container-fluid d-flex align-items-center">
    <div class="container justify-content-center py-4 py-md-0 mt-4">
        <h2 class="text-center">{% trans "Are you sure delete " %}{{ device.device_model }}?</h2>
        
        <div class="row">
            <form method="post" class="text-center">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-danger my-4">{% trans "Delete" %}</button>
            </form>
        </div>
    </div>
</section>
{% endblock content %}

cms/templates/cms/disease.html
{% extends '_base.html' %}
{% load i18n %}
{% load bootstrap4 %}

{% block head %}
    <title>Longevity InTime - {% trans 'Disease' %}</title>
{% endblock head %}

{% block content %}
<section class="main disease container-fluid d-flex align-items-center">
    <div class="container align-items-center mt-4">
        <section class="text-left text-secondary my-4 py-4 mx-lg-5 px-lg-5">
            <div class="mb-4 py-4 row px-lg-5 mx-lg-5">
                <div class="col-12 col-lg-3 text-left pt-2 mb-4">
                    <a href="{% url 'users:profile' %}">
                        {% include 'includes/back-button.html' %}
                    </a>
                </div>

                <h1 class="col text-uppercase section-heading text-dark text-center">
                    {% trans 'Disease' %}
                </h1>

                <div class="col-12 col-lg-3 text-right mt-4 mt-lg-0"></div>
            </div>

            <form method="post" class="text-secondary text-left my-4 py-4">
                <h4 class="text-uppercase section-heading text-dark text-center mb-4 py-4">
                    {% trans 'Diseases of the cardiovascular system' %}
                </h4>

                {% csrf_token %}

                <div>{% trans 'Blood pressure related' %}</div>
                {% bootstrap_field form.disease_blood_pressure show_label=False %}

                <div>{% trans 'Associated with abnormal heart rhythm' %}</div>
                {% bootstrap_field form.disease_heart_rate show_label=False %}

                <h4 class="text-uppercase section-heading text-dark text-center mb-4 py-4">
                    {% trans 'Diseases associated with nutritional and metabolic disorders' %}
                </h4>

                {% bootstrap_field form.disease_obesity show_label=False %}

                <div class="text-center">
                    <button class="btn btn-primary my-3" type="submit">{% trans 'Save' %}</button>
                </div>
            </form>
        </section>
    </div>
</section>
{% endblock content %}

cms/templates/cms/empty_data.html
{% extends '_base.html' %} {% load i18n %} {% block head %}
<title>Longevity InTime - {% trans 'Email address confirmed' %}</title>
{% endblock head %} {% block content %}

<section class="main empty-data container-fluid d-flex align-items-center">
  <div class="container justify-content-center mt-4">
    <section class="my-4">
      <a href="{% url 'cms:dashboard' %}">
        {% include 'includes/back-button.html' %}
        <span class="mx-4">{% trans 'Dashboard' %}</span>
      </a>
    </section>

    <section class="container justify-content-center py-4 py-md-0 mt-4">
      <h1 class="text-uppercase section-heading text-dark text-center mb-4 py-4">
        {% trans 'You did not enter any data' %}
      </h1>

      {% for key in data %}
      <p class="mx-lg-5 px-lg-5">{{ key }}</p>
      {% endfor %}
    </section>

    <section class="my-4 pb-4">
      <a href="{% url 'cms:dashboard' %}">
        {% include 'includes/back-button.html' %}
        <span class="mx-4">{% trans 'Dashboard' %}</span>
      </a>
    </section>
  </div>
</section>
{% endblock content %}

cms/templates/cms/recommendation.html
{% extends '_base.html' %}
{% load i18n %}
{% load bootstrap4 %}

{% block head %}
<title>Longevity InTime - {% trans 'Recommendations' %}</title>
{% endblock head %}

{% block content %}
<section class="main dashboard container-fluid d-flex align-items-center">
    <div class="container align-items-center mt-4 px-0">
        <section class="text-left text-secondary my-4 py-4 mx-lg-5 px-lg-5">
            <div class="mb-4 py-4 row px-lg-5 mx-lg-5">
                <div class="col-12 col-lg-2 text-left pt-2 mb-4">
                    <a href="{% url 'cms:dashboard' %}">
                        {% include 'includes/back-button.html' %}
                    </a>
                </div>

                <h1 class="col text-uppercase section-heading text-dark text-center">
                    {% trans 'Recommendations' %}
                </h1>

                <div class="col-12 col-lg-2 text-right mt-4 mt-lg-0"></div>
            </div>

            <section class="text-left text-secondary mb-2 pb-2 px-lg-5 mx-lg-5">
                <section class="text-left text-secondary mb-4 pb-4">
                    {% for r in rec %}
                        <div class="card card-body shadow mb-2">{{ r }}</div>
                    {% endfor %}
                </section>

                <hr width="100%" />

                <div class="my-2 py-2 px-2">
                    <small class="text-secondary">
                        <em>{% trans 'Consult a specialist. It is not a medical application.' %}</em>
                    </small>
                </div>
            </section>
        </section>
    </div>
</section>
{% endblock content %}